# =============================================================================
# MFA Configuration - Analysis-Driven Architecture
# =============================================================================

# Directory paths
paths:
  output_dir: outputs/extracted_json
  analysis_dir: outputs/analysis

# Global scraping settings (shared across all analyses)
scraping:
  headless: false              # Set to true to hide browser window
  timeout_seconds: 30          # How long to wait for pages to load
  delay_between_requests: 1.0  # Seconds to wait between scraping each fund
  save_extracted_json: true    # Save intermediate scraped JSON files to disk

# Output formatting
output:
  filename_prefix: "coin_"     # Prefix for scraped data files
  include_date_in_folder: true # Create date-based folders (YYYYMMDD)

# Analysis definitions - each analysis defines its own data requirements
analyses:
  holdings:
    enabled: true
    type: fund-holdings
    # Note: No path_template specified, so uses smart defaults:
    # outputs/extracted_json/{date}/holdings/{category}/ for scraped data
    # outputs/analysis/{date}/ for analysis results
    data_requirements:
      scraping_strategy: categories
      categories:
          largeCap:
            - https://coin.zerodha.com/mf/fund/INF204K01XI3/nippon-india-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF109K016L0/icici-prudential-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF179K01YV8/hdfc-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF200K01QX4/sbi-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF251K01HN7/baroda-bnp-paribas-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF760K01FR2/canara-robeco-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF247L01CE3/motilal-oswal-large-cap-fund-direct-growth
          midCap:
            - https://coin.zerodha.com/mf/fund/INF179K01XQ0/hdfc-mid-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF174K01LT0/kotak-midcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF204K01E54/nippon-india-growth-mid-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF247L01445/motilal-oswal-midcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF200K01TP4/sbi-midcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF846K01EH3/axis-midcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF769K01FA9/mirae-asset-midcap-fund-direct-growth
          smallCap:
            - https://coin.zerodha.com/mf/fund/INF204K01K15/nippon-india-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF179KA1RW5/hdfc-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF200K01T51/sbi-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF846K01K35/axis-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF966L01689/quant-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF760K01JC6/canara-robeco-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF109K015M0/icici-prudential-smallcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF247L01BY3/motilal-oswal-small-cap-fund-direct-growth
    params:
      max_holdings: 10                    # Number of top holdings to extract per fund
      max_companies_in_results: 100
      max_sample_funds_per_company: 10
      exclude_from_analysis:
        - "TREPS"        # Treasury Repo
        - "CASH"         # Cash holdings  
        - "T-BILLS"      # Treasury Bills
        - "REVERSE REPO" # Reverse Repo
        - "REPO"         # Repo
        - "CBLO"         # Collateralized Borrowing

  # Future portfolio analysis example with custom path template:
  # portfolio:
  #   enabled: false
  #   type: portfolio-composition
  #   data_requirements:
  #     scraping_strategy: targeted_funds
  #     funds:
  #       - units: 1000
  #         url: https://coin.zerodha.com/mf/fund/INF204K01XI3/nippon-india-large-cap-fund-direct-growth
  #       - units: 500
  #         url: https://coin.zerodha.com/mf/fund/INF179K01YV8/hdfc-large-cap-fund-direct-growth
  #   params:
  #     max_holdings: 50                  # Portfolio analysis needs more detailed holdings
  #     target_investment: 100000
  #     chart_top_n: 20
  #     exclude_from_analysis:
  #       - "TREPS"
  #       - "CASH"
  #   # Optional: Custom path template (if not specified, uses smart defaults)
  #   # Smart default for portfolio would be: outputs/extracted_json/{date}/portfolio/
  #   # path_template: "{output_dir}/{date}/portfolio"
  #   # analysis_output_template: "{analysis_dir}/{date}/portfolio" 