paths:
  output_dir: outputs/extracted_json
  analysis_dir: outputs/analysis

scraping:
  engine: playwright
  concurrent_requests: 10
  playwright:
    headless: false


funds:
  largeCap:
    - https://coin.zerodha.com/mf/fund/INF204K01XI3/nippon-india-large-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF109K016L0/icici-prudential-large-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF179K01YV8/hdfc-large-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF200K01QX4/sbi-large-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF251K01HN7/baroda-bnp-paribas-large-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF760K01FR2/canara-robeco-large-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF247L01CE3/motilal-oswal-large-cap-fund-direct-growth
  midCap:
    - https://coin.zerodha.com/mf/fund/INF179K01XQ0/hdfc-mid-cap-fund-direct-growth
  smallCap:
    - https://coin.zerodha.com/mf/fund/INF204K01K15/nippon-india-small-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF179KA1RW5/hdfc-small-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF200K01T51/sbi-small-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF846K01K35/axis-small-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF966L01689/quant-small-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF760K01JC6/canara-robeco-small-cap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF109K015M0/icici-prudential-smallcap-fund-direct-growth
    - https://coin.zerodha.com/mf/fund/INF247L01BY3/motilal-oswal-small-cap-fund-direct-growth
