paths:
  output_dir: outputs/extracted_json
  analysis_dir: outputs/analysis

# Global scraping settings (shared across all analyses)
scraping:
  timeout_seconds: 30          # How long to wait for pages to load
  delay_between_requests: .1  # Seconds to wait between scraping each fund
  save_extracted_json: true    # Save intermediate scraped JSON files to disk
  default_scraper: api         # Default scraper type: "api" or "playwright"

# Analysis definitions - each analysis defines its own data requirements
analyses:
  holdings:                    # Key IS the analyzer type (removed redundant type field)
    enabled: true
    data_requirements:
      scraping_strategy: categories    # Strategy: how data is organized
      scraper_type: api               # Scraper: what technology to use
      categories:
          largeCap:
            - https://coin.zerodha.com/mf/fund/INF204K01XI3/nippon-india-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF109K016L0/icici-prudential-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF179K01YV8/hdfc-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF200K01QX4/sbi-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF251K01HN7/baroda-bnp-paribas-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF760K01FR2/canara-robeco-large-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF247L01CE3/motilal-oswal-large-cap-fund-direct-growth
          midCap:
            - https://coin.zerodha.com/mf/fund/INF179K01XQ0/hdfc-mid-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF174K01LT0/kotak-midcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF204K01E54/nippon-india-growth-mid-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF247L01445/motilal-oswal-midcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF200K01TP4/sbi-midcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF846K01EH3/axis-midcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF769K01FA9/mirae-asset-midcap-fund-direct-growth
          smallCap:
            - https://coin.zerodha.com/mf/fund/INF204K01K15/nippon-india-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF179KA1RW5/hdfc-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF200K01T51/sbi-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF846K01K35/axis-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF966L01689/quant-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF760K01JC6/canara-robeco-small-cap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF109K015M0/icici-prudential-smallcap-fund-direct-growth
            - https://coin.zerodha.com/mf/fund/INF247L01BY3/motilal-oswal-small-cap-fund-direct-growth
    params:
      max_holdings: 50                    # API can handle more efficiently
      max_companies_in_results: 100
      max_sample_funds_per_company: 10
      exclude_from_analysis:
        - "TREPS"        # Treasury Repo
        - "CASH"         # Cash holdings  
        - "T-BILLS"      # Treasury Bills
        - "REVERSE REPO" # Reverse Repo
        - "REPO"         # Repo
        - "CBLO"         # Collateralized Borrowing

  portfolio:          # Key IS the analyzer type (matches @register_analyzer)
    enabled: true
    data_requirements:
      scraping_strategy: targeted_funds   # Strategy: how data is organized
      scraper_type: api                  # Scraper: what technology to use
      funds:
        - units: 1000
          url: https://coin.zerodha.com/mf/fund/INF204K01XI3/nippon-india-large-cap-fund-direct-growth
        - units: 500
          url: https://coin.zerodha.com/mf/fund/INF179K01YV8/hdfc-large-cap-fund-direct-growth
        - units: 400
          url: https://coin.zerodha.com/mf/fund/INF204K01K15/nippon-india-small-cap-fund-direct-growth
        - units: 300
          url: https://coin.zerodha.com/mf/fund/INF846K01EH3/axis-midcap-fund-direct-growth
        - units: 200
          url: https://coin.zerodha.com/mf/fund/INF179K01XQ0/hdfc-mid-cap-fund-direct-growth
    params:
      max_holdings: 50                  # Portfolio analysis needs more detailed holdings
      chart_top_n: 20
